name: .NET Backend CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --no-restore --configuration Release

    - name: Test
      run: dotnet test --no-build --verbosity normal

    # 🔥 New Step 1: Publish the API
    - name: Publish Backend
      run: dotnet publish ./RealEstatePortal.csproj -c Release -o ./publish

    # 🔥 New Step 2: Upload the published build as an artifact
    - name: Upload Build Artifact
      uses: actions/upload-artifact@v4
      with:
        name: backend-build
        path: ./publish
