name: .NET Backend CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Find solution file
        run: |
          echo "Solution files in repo:"
          ls -la *.sln || true

      - name: Restore NuGet packages
        run: dotnet restore ./RealEstatePortal.sln

      - name: Build solution
        run: dotnet build ./RealEstatePortal.sln --no-restore --configuration Release

      - name: Run tests
        run: dotnet test ./RealEstatePortal.sln --no-build --verbosity normal
